# Generated by Django 5.1.4 on 2025-03-22 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Task',
            new_name='task',
        ),
    ]
